# Generated by Django 5.1.7 on 2025-03-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='publisher',
            name='address',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='city',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='state_provine',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
