# Generated by Django 5.1.7 on 2025-03-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0002_musician_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshamn'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
