# Generated by Django 5.1.7 on 2025-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0003_person_year_in_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='my_type',
            field=models.CharField(blank=True, choices=[('Type01', 'Type01')], max_length=8),
        ),
    ]
