# Generated by Django 5.1.7 on 2025-03-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0005_alter_person_my_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='person first name'),
        ),
    ]
