# Generated by Django 5.1.7 on 2025-03-16 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0006_alter_person_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_name', models.CharField(max_length=100, verbose_name='manugacturer name')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_models.manufacturer')),
            ],
        ),
    ]
