# Generated by Django 5.1.7 on 2025-03-19 02:53
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0008_group_membership_group_members_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
