# Generated by Django 5.1.7 on 2025-03-19 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0009_alter_person_options_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
